sudo: false
language: ruby
rvm:
- 2.2.2
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
script:
- git clone https://github.com/saasbook/hw-ruby-intro-ci
notifications:
  email: false
  slack: cs169dev:OPMf1tPzfO3a4gz6gGTOFV7w
